name: sample-laravel
services:
- environment_slug: php
  name: web
  github:
    branch: main
    deploy_on_push: false
    repo: JonathanBowker/ranulph
  build_command: composer install --no-interaction --prefer-dist --optimize-autoloader && npm ci && npm run build
  run_command: mkdir -p /tmp/laravel-sessions && touch /tmp/database.sqlite && php artisan migrate --force && heroku-php-apache2 public/
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: https://sample-laravel-h4bwp.ondigitalocean.app
  - key: APP_KEY
    scope: RUN_TIME
    type: SECRET
    value: ${APP_KEY}
  - key: SESSION_DRIVER
    value: file
  - key: SESSION_FILES
    value: /tmp/laravel-sessions
  - key: SESSION_SECURE_COOKIE
    value: "true"
  - key: DB_CONNECTION
    value: sqlite
  - key: DB_DATABASE
    value: /tmp/database.sqlite
  http_port: 8080
  source_dir: /
