name: sample-laravel
services:
- environment_slug: php
  name: web
  github:
    branch: main
    deploy_on_push: false
    repo: JonathanBowker/ranulph
  build_command: composer install --no-interaction --prefer-dist --optimize-autoloader && npm ci && npm run build
  run_command: heroku-php-apache2 public/
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_KEY
    scope: RUN_TIME
    type: SECRET
    value: ${APP_KEY}
  http_port: 8080
  source_dir: /
